language: node_js
node_js:
  - "9.2.0"
sudo: false
cache:
  directories:
    - node_modules
script:
  - "npm run test"
after_success:
  - "npm run coveralls"

deploy:
  provider: heroku
  api_key: $API_KEY
  app: vehicles-table